### PR TITLE
Upgrade apache-php7(-drupal) to PHP 7.1

### PR DESCRIPTION
**Pull request by q0rban**

### CODE REVIEW

**Comment by bchavet** [comment]
I think I would rather see this as a new image. Maybe apache-php7_1 (because we still have problems with "." in the image names)?

Ultimately, I want to support docker image tags, so we can be cleaner about this sort of thing, but until then, I want to maintain expectations about a given image. For example, if you're expecting php7.0, but then one day you start getting 7.1, that might cause problems.

**Comment by q0rban** [comment]
That's fine, however PHP 7.0 is no longer a recommended version for many applications, and in 8 months will [no longer be receiving security updates](http://php.net/supported-versions.php). 

Here's [Drupal 8's current PHP version requirements](https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements): 
drupal 8 php requirements drupal 8 guide on drupal org 2018-03-23 08-55-18

**Comment by mrdavidburns** [comment]
👍

**Comment by bchavet** [comment]
I still think I'd rather have this as a new image name. There are already a number of build scripts in service that assume php7.0, many of which even upgrade to php7.1. Without auditing each of them, it's impossible to say whether changing the php version on the image would do unpredictable things.

We can decommission the php7.0 image when the time comes that it's no longer safe.

**Pull request closed without merging**
